services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Give MySQL time to initialize before checking

  api:
    build: .
    volumes:
      - .:/app  # This links YOUR current folder (.) to the container's /app folder
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:${MYSQL_PASSWORD}@db:3306/${MYSQL_DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"

volumes:
  db_data: 